# action.yaml
name: 'Slack Messages'
description: 'This github action can be used to send automatic slack message'
inputs:
  message:
    description: 'Enter a number'
    required: true
    default: "1"
# outputs:
#   num_squared:
#     description: 'Square of the input'
#     # need to specify the extra `value` field for `composite` actions
#     value: ${{ steps.get-square.outputs.num_squared }}
runs:
  using: 'composite'
  steps:
#     - name: Install Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.10'  
#     - name: Install Dependencies
#       run: pip install -r requirements.txt
#       shell: bash
#     - name: Pass Inputs to Shell
#       run: |
#        echo "INPUT_NUM=${{ inputs.num }}" >> $GITHUB_ENV
#       shell: bash
    - uses: ashthetis/slack-message-action@main
    - name: Send Slack Message
      run: |
        pwd
        ls
        python slack_auto.py
      shell: bash
